version: '3.4'

services:
  ae-code-test-api:
    image: ${DOCKER_REGISTRY-}aecodetestapi
    build:
      context: .
      dockerfile: AE-Code-Test-API/Dockerfile
    ports:
        - "80:80"
    expose:  
      - 80
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=p@ssw0rd
        - ACCEPT_EULA=Y
    ports:
        - "1440:1433"
    expose:  
      - 1440