// <auto-generated />
using System;
using AE_Code_Test_API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AE_Code_Test_API.Migrations
{
    [DbContext(typeof(AEContext))]
    [Migration("20220708144358_1_0_0")]
    partial class _1_0_0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AE_Code_Test_API.Entities.Port", b =>
                {
                    b.Property<int>("PortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortId"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PortId");

                    b.ToTable("Port");

                    b.HasData(
                        new
                        {
                            PortId = 1,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1280),
                            Latitude = -17.375094893872074,
                            Longitude = 64.813785519925574,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1293),
                            Name = "Port1"
                        },
                        new
                        {
                            PortId = 2,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1315),
                            Latitude = 52.828049005762864,
                            Longitude = -105.65597772252674,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1316),
                            Name = "Port2"
                        },
                        new
                        {
                            PortId = 3,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1318),
                            Latitude = 58.350533142905505,
                            Longitude = 153.53914153465064,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1319),
                            Name = "Port3"
                        },
                        new
                        {
                            PortId = 4,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1323),
                            Latitude = 19.544001131766578,
                            Longitude = -140.91694014506194,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1323),
                            Name = "Port4"
                        },
                        new
                        {
                            PortId = 5,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1325),
                            Latitude = 40.199608247573565,
                            Longitude = 138.05132866272197,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1326),
                            Name = "Port5"
                        },
                        new
                        {
                            PortId = 6,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1331),
                            Latitude = 37.776125603431154,
                            Longitude = 98.330554994108979,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1331),
                            Name = "Port6"
                        },
                        new
                        {
                            PortId = 7,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1334),
                            Latitude = -82.928884659401731,
                            Longitude = 81.197981161304597,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1334),
                            Name = "Port7"
                        },
                        new
                        {
                            PortId = 8,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1337),
                            Latitude = -81.192463109940604,
                            Longitude = 75.647680491294409,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1338),
                            Name = "Port8"
                        },
                        new
                        {
                            PortId = 9,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1340),
                            Latitude = -7.8098116361208128,
                            Longitude = 29.508601305324731,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1340),
                            Name = "Port9"
                        },
                        new
                        {
                            PortId = 10,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1345),
                            Latitude = 26.610538158517599,
                            Longitude = -159.08454759663209,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1346),
                            Name = "Port10"
                        },
                        new
                        {
                            PortId = 11,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1348),
                            Latitude = 65.6455047223169,
                            Longitude = 25.917608935325489,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1349),
                            Name = "Port11"
                        },
                        new
                        {
                            PortId = 12,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1352),
                            Latitude = 50.783112224694463,
                            Longitude = 103.77230367615374,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1353),
                            Name = "Port12"
                        },
                        new
                        {
                            PortId = 13,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1355),
                            Latitude = -5.5385125438267266,
                            Longitude = 93.823584150209683,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1355),
                            Name = "Port13"
                        },
                        new
                        {
                            PortId = 14,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1359),
                            Latitude = -77.735361638272934,
                            Longitude = -179.77986971346235,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1359),
                            Name = "Port14"
                        },
                        new
                        {
                            PortId = 15,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1361),
                            Latitude = -13.538906344575992,
                            Longitude = 153.26884864349853,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1361),
                            Name = "Port15"
                        },
                        new
                        {
                            PortId = 16,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1365),
                            Latitude = -74.897328462678502,
                            Longitude = -64.801723928084897,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1365),
                            Name = "Port16"
                        },
                        new
                        {
                            PortId = 17,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1367),
                            Latitude = 81.426047900640782,
                            Longitude = 67.065835676266261,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1367),
                            Name = "Port17"
                        },
                        new
                        {
                            PortId = 18,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1372),
                            Latitude = -24.021020038184048,
                            Longitude = -75.716057008991271,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1373),
                            Name = "Port18"
                        },
                        new
                        {
                            PortId = 19,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1375),
                            Latitude = -23.78312019719715,
                            Longitude = -123.02849704466301,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1375),
                            Name = "Port19"
                        },
                        new
                        {
                            PortId = 20,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1379),
                            Latitude = 56.29908757353752,
                            Longitude = 7.8900441858908721,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1379),
                            Name = "Port20"
                        },
                        new
                        {
                            PortId = 21,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1381),
                            Latitude = 32.140673062789702,
                            Longitude = 162.25419101302697,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1382),
                            Name = "Port21"
                        },
                        new
                        {
                            PortId = 22,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1385),
                            Latitude = 20.569412542179194,
                            Longitude = 78.469058686475705,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1386),
                            Name = "Port22"
                        },
                        new
                        {
                            PortId = 23,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1388),
                            Latitude = -67.502403065252111,
                            Longitude = -129.84506870225187,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1388),
                            Name = "Port23"
                        },
                        new
                        {
                            PortId = 24,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1391),
                            Latitude = -41.969275623802268,
                            Longitude = -90.712365130010255,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1392),
                            Name = "Port24"
                        },
                        new
                        {
                            PortId = 25,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1394),
                            Latitude = -33.349117799323004,
                            Longitude = -153.79880065405217,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1394),
                            Name = "Port25"
                        },
                        new
                        {
                            PortId = 26,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1433),
                            Latitude = -45.586422592074776,
                            Longitude = -84.107663339996861,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1433),
                            Name = "Port26"
                        },
                        new
                        {
                            PortId = 27,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1436),
                            Latitude = -89.757369502250683,
                            Longitude = -39.595365380428206,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1436),
                            Name = "Port27"
                        },
                        new
                        {
                            PortId = 28,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1440),
                            Latitude = -32.338975080649163,
                            Longitude = -143.5196888179164,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1441),
                            Name = "Port28"
                        },
                        new
                        {
                            PortId = 29,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1443),
                            Latitude = 33.509224000098044,
                            Longitude = 29.387282054795918,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1443),
                            Name = "Port29"
                        },
                        new
                        {
                            PortId = 30,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1446),
                            Latitude = -69.566168956570337,
                            Longitude = -145.50646781813802,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1447),
                            Name = "Port30"
                        },
                        new
                        {
                            PortId = 31,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1449),
                            Latitude = 70.675264026159624,
                            Longitude = -146.96860872814364,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1449),
                            Name = "Port31"
                        },
                        new
                        {
                            PortId = 32,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1452),
                            Latitude = -1.4049433510576108,
                            Longitude = -152.28076160345117,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1453),
                            Name = "Port32"
                        },
                        new
                        {
                            PortId = 33,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1455),
                            Latitude = 74.969838454385155,
                            Longitude = -149.90789783791018,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1455),
                            Name = "Port33"
                        },
                        new
                        {
                            PortId = 34,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1460),
                            Latitude = -67.017953249010361,
                            Longitude = -63.459276194018557,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1460),
                            Name = "Port34"
                        },
                        new
                        {
                            PortId = 35,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1463),
                            Latitude = -38.769647964687316,
                            Longitude = -112.36102578413528,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1463),
                            Name = "Port35"
                        },
                        new
                        {
                            PortId = 36,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1466),
                            Latitude = 21.989464564021844,
                            Longitude = -75.669266455501258,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1467),
                            Name = "Port36"
                        },
                        new
                        {
                            PortId = 37,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1469),
                            Latitude = 49.854774375416525,
                            Longitude = 162.13780547916463,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1469),
                            Name = "Port37"
                        },
                        new
                        {
                            PortId = 38,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1472),
                            Latitude = 22.69544467305596,
                            Longitude = -122.7095513030163,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1473),
                            Name = "Port38"
                        },
                        new
                        {
                            PortId = 39,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1475),
                            Latitude = -28.686935409173017,
                            Longitude = 75.879697187817925,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1475),
                            Name = "Port39"
                        },
                        new
                        {
                            PortId = 40,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1479),
                            Latitude = -36.842684619971465,
                            Longitude = -73.028303901892542,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1479),
                            Name = "Port40"
                        },
                        new
                        {
                            PortId = 41,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1481),
                            Latitude = 18.465712935269352,
                            Longitude = 150.9541777253279,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1482),
                            Name = "Port41"
                        },
                        new
                        {
                            PortId = 42,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1485),
                            Latitude = -58.2501390739111,
                            Longitude = 67.169399852253662,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1485),
                            Name = "Port42"
                        },
                        new
                        {
                            PortId = 43,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1487),
                            Latitude = 54.373802623079627,
                            Longitude = -75.113315843304264,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1488),
                            Name = "Port43"
                        },
                        new
                        {
                            PortId = 44,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1491),
                            Latitude = -88.180090162238486,
                            Longitude = -55.342058695356585,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1491),
                            Name = "Port44"
                        },
                        new
                        {
                            PortId = 45,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1493),
                            Latitude = -68.458162614936981,
                            Longitude = 63.527684292998487,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1493),
                            Name = "Port45"
                        },
                        new
                        {
                            PortId = 46,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1497),
                            Latitude = -51.806535382855593,
                            Longitude = -2.6842391475284444,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1497),
                            Name = "Port46"
                        },
                        new
                        {
                            PortId = 47,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1499),
                            Latitude = -11.887189590648219,
                            Longitude = -36.026864807001743,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1499),
                            Name = "Port47"
                        },
                        new
                        {
                            PortId = 48,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1502),
                            Latitude = -71.781980194889528,
                            Longitude = -3.1309083830570046,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1503),
                            Name = "Port48"
                        },
                        new
                        {
                            PortId = 49,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1505),
                            Latitude = -61.305689537417464,
                            Longitude = -149.34819782905836,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1505),
                            Name = "Port49"
                        },
                        new
                        {
                            PortId = 50,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1508),
                            Latitude = 83.432349072023527,
                            Longitude = -134.02364504348279,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1509),
                            Name = "Port50"
                        },
                        new
                        {
                            PortId = 51,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1511),
                            Latitude = -18.004187889972826,
                            Longitude = -139.26570607184118,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1511),
                            Name = "Port51"
                        },
                        new
                        {
                            PortId = 52,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1514),
                            Latitude = -28.139297687130195,
                            Longitude = 89.946826092583706,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1514),
                            Name = "Port52"
                        },
                        new
                        {
                            PortId = 53,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1538),
                            Latitude = -72.547033777522074,
                            Longitude = -130.71693945440938,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1538),
                            Name = "Port53"
                        },
                        new
                        {
                            PortId = 54,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1543),
                            Latitude = -9.1429885074365842,
                            Longitude = -101.76729643158068,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1543),
                            Name = "Port54"
                        },
                        new
                        {
                            PortId = 55,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1545),
                            Latitude = -61.805371212033172,
                            Longitude = -167.27166351056988,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1546),
                            Name = "Port55"
                        },
                        new
                        {
                            PortId = 56,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1549),
                            Latitude = -19.93232453114058,
                            Longitude = 50.557354728974275,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1549),
                            Name = "Port56"
                        },
                        new
                        {
                            PortId = 57,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1552),
                            Latitude = -34.697994055458736,
                            Longitude = -87.202914363071713,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1552),
                            Name = "Port57"
                        },
                        new
                        {
                            PortId = 58,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1555),
                            Latitude = 48.448651559887224,
                            Longitude = -3.0303745780889244,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1555),
                            Name = "Port58"
                        },
                        new
                        {
                            PortId = 59,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1557),
                            Latitude = 68.589718564963903,
                            Longitude = -105.0975134287857,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1558),
                            Name = "Port59"
                        },
                        new
                        {
                            PortId = 60,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1561),
                            Latitude = 66.257037120184521,
                            Longitude = -27.687736174291302,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1561),
                            Name = "Port60"
                        },
                        new
                        {
                            PortId = 61,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1563),
                            Latitude = 19.318474633064227,
                            Longitude = 148.63960339723707,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1564),
                            Name = "Port61"
                        },
                        new
                        {
                            PortId = 62,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1568),
                            Latitude = 45.650279816687373,
                            Longitude = -81.113073285287129,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1568),
                            Name = "Port62"
                        },
                        new
                        {
                            PortId = 63,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1570),
                            Latitude = 35.277733793545821,
                            Longitude = -144.09399499821609,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1570),
                            Name = "Port63"
                        },
                        new
                        {
                            PortId = 64,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1574),
                            Latitude = -79.17619553407836,
                            Longitude = 42.712134545968695,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1574),
                            Name = "Port64"
                        },
                        new
                        {
                            PortId = 65,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1576),
                            Latitude = 6.6102714821271604,
                            Longitude = 116.16478033653902,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1577),
                            Name = "Port65"
                        },
                        new
                        {
                            PortId = 66,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1582),
                            Latitude = 38.108774609553194,
                            Longitude = 179.50642139773083,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1582),
                            Name = "Port66"
                        },
                        new
                        {
                            PortId = 67,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1584),
                            Latitude = 32.11574077595921,
                            Longitude = -156.14052462655849,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1585),
                            Name = "Port67"
                        },
                        new
                        {
                            PortId = 68,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1588),
                            Latitude = -62.317213339862874,
                            Longitude = 63.141587603878094,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1589),
                            Name = "Port68"
                        },
                        new
                        {
                            PortId = 69,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1591),
                            Latitude = 4.3471417921398938,
                            Longitude = 10.537014746733831,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1591),
                            Name = "Port69"
                        },
                        new
                        {
                            PortId = 70,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1594),
                            Latitude = -38.334026513722833,
                            Longitude = -160.31067400329633,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1595),
                            Name = "Port70"
                        },
                        new
                        {
                            PortId = 71,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1597),
                            Latitude = 28.097799144322892,
                            Longitude = -52.713730318599048,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1597),
                            Name = "Port71"
                        },
                        new
                        {
                            PortId = 72,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1600),
                            Latitude = 75.737282062147273,
                            Longitude = 78.601805565052985,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1601),
                            Name = "Port72"
                        },
                        new
                        {
                            PortId = 73,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1603),
                            Latitude = 66.582337289062934,
                            Longitude = -57.078337069853461,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1603),
                            Name = "Port73"
                        },
                        new
                        {
                            PortId = 74,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1606),
                            Latitude = -13.887925170498505,
                            Longitude = 157.25155471879987,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1607),
                            Name = "Port74"
                        },
                        new
                        {
                            PortId = 75,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1608),
                            Latitude = 82.569627546559843,
                            Longitude = -55.304374295120937,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1609),
                            Name = "Port75"
                        },
                        new
                        {
                            PortId = 76,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1612),
                            Latitude = 16.677283553542054,
                            Longitude = 34.669632133694051,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1612),
                            Name = "Port76"
                        },
                        new
                        {
                            PortId = 77,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1614),
                            Latitude = -44.792671492969987,
                            Longitude = 83.224077444462296,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1615),
                            Name = "Port77"
                        },
                        new
                        {
                            PortId = 78,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1618),
                            Latitude = 54.596544946752488,
                            Longitude = 41.348187704319173,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1618),
                            Name = "Port78"
                        },
                        new
                        {
                            PortId = 79,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1642),
                            Latitude = -89.212004011592228,
                            Longitude = 101.9936811625758,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1642),
                            Name = "Port79"
                        },
                        new
                        {
                            PortId = 80,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1646),
                            Latitude = 25.133555192971784,
                            Longitude = -170.77405255581249,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1646),
                            Name = "Port80"
                        },
                        new
                        {
                            PortId = 81,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1648),
                            Latitude = 55.755996292995519,
                            Longitude = -136.38972405142209,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1649),
                            Name = "Port81"
                        },
                        new
                        {
                            PortId = 82,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1652),
                            Latitude = -87.686581898332733,
                            Longitude = 88.068370575704478,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1652),
                            Name = "Port82"
                        },
                        new
                        {
                            PortId = 83,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1654),
                            Latitude = 61.960100808027619,
                            Longitude = 17.244878981721342,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1655),
                            Name = "Port83"
                        },
                        new
                        {
                            PortId = 84,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1658),
                            Latitude = -41.00930890621418,
                            Longitude = 48.40398849013738,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1658),
                            Name = "Port84"
                        },
                        new
                        {
                            PortId = 85,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1660),
                            Latitude = -27.382471782754912,
                            Longitude = -94.497182421009143,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1661),
                            Name = "Port85"
                        },
                        new
                        {
                            PortId = 86,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1664),
                            Latitude = 84.330290965151022,
                            Longitude = -40.722083102205545,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1664),
                            Name = "Port86"
                        },
                        new
                        {
                            PortId = 87,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1667),
                            Latitude = 72.00668908088582,
                            Longitude = -129.84851963629089,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1667),
                            Name = "Port87"
                        },
                        new
                        {
                            PortId = 88,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1671),
                            Latitude = -66.647562097223272,
                            Longitude = 119.30411146360785,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1671),
                            Name = "Port88"
                        },
                        new
                        {
                            PortId = 89,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1673),
                            Latitude = -54.508279312233583,
                            Longitude = 117.84792949385911,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1673),
                            Name = "Port89"
                        },
                        new
                        {
                            PortId = 90,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1676),
                            Latitude = 49.945080258232792,
                            Longitude = 22.956327002384484,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1677),
                            Name = "Port90"
                        },
                        new
                        {
                            PortId = 91,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1679),
                            Latitude = 67.036838625655861,
                            Longitude = 12.372517592177388,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1679),
                            Name = "Port91"
                        },
                        new
                        {
                            PortId = 92,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1682),
                            Latitude = -40.769891142045239,
                            Longitude = -87.799270937136853,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1683),
                            Name = "Port92"
                        },
                        new
                        {
                            PortId = 93,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1684),
                            Latitude = -6.1063054803812804,
                            Longitude = -142.22080643673326,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1685),
                            Name = "Port93"
                        },
                        new
                        {
                            PortId = 94,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1688),
                            Latitude = -12.797521981436432,
                            Longitude = -100.04798213735316,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1688),
                            Name = "Port94"
                        },
                        new
                        {
                            PortId = 95,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1690),
                            Latitude = -3.1761643958206633,
                            Longitude = -6.4439283305517563,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1691),
                            Name = "Port95"
                        },
                        new
                        {
                            PortId = 96,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1694),
                            Latitude = 46.834048135438536,
                            Longitude = 71.181620558335737,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1694),
                            Name = "Port96"
                        },
                        new
                        {
                            PortId = 97,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1696),
                            Latitude = -49.698664883152354,
                            Longitude = 33.779923874213011,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1696),
                            Name = "Port97"
                        },
                        new
                        {
                            PortId = 98,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1700),
                            Latitude = -13.095410207427719,
                            Longitude = 169.8315154325162,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1700),
                            Name = "Port98"
                        },
                        new
                        {
                            PortId = 99,
                            CreateDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1702),
                            Latitude = 64.413000776726392,
                            Longitude = 25.765547340329505,
                            ModifyDate = new DateTime(2022, 7, 8, 22, 43, 57, 897, DateTimeKind.Local).AddTicks(1702),
                            Name = "Port99"
                        });
                });

            modelBuilder.Entity("AE_Code_Test_API.Entities.Ship", b =>
                {
                    b.Property<int>("ShipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipId"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("VelocityKmh")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ShipId");

                    b.ToTable("Ship");
                });
#pragma warning restore 612, 618
        }
    }
}
